### ISSUE TITLE
[Submission] Daydream Mini

### ISSUE THREAD

**Issue by eliminate123** [Warzone/PublicMaps#109]
### Map Name

Daydream Mini

### Map Description & Gamemode

4 Team 6v6v6v6 CTW. This is a mini version of Hillside Daydream

### Map XML

https://gist.github.com/eliminate123/4359f5e46a361c9bafeaa555f98c124e

### Screenshot

![image](https://user-images.githubusercontent.com/96848330/204153375-a85fd1c7-c620-40f6-8fa9-ecb3582febec.png)
![image](https://user-images.githubusercontent.com/96848330/204153385-acd0419a-ae84-4866-9661-ec1b03c7e85e.png)
![image](https://user-images.githubusercontent.com/96848330/204153393-080cc2a4-e249-4b46-b146-275d24707d1e.png)

### Map Download

[Daydream Mini.zip](https://github.com/Warzone/PublicMaps/files/10098938/Daydream.Mini.zip)

### Checklist

- [X] Contains a map.xml file with valid syntax and formatting.
- [X] The map.xml uses proto 1.4.0 or above (older or legacy maps are exempt, so long as the XML works).
- [X] The map.xml explicitly sets the gamemode (for stat-tracking).
- [X] The map.xml has correctly credited the map authors and contributors.
- [X] Contains map.png file (290x246).
- [X] The map was built for (or has been converted to) Minecraft 1.8.
- [X] Chunks have been pruned.
- [X] The map has been tested on a server running PGM.
- [X] I agree to submit this map under a commercial, CC BY-SA 4.0 license.

**Comment by BTKingly** [comment]
This was never closed when map was loaded on server, doing it now.
