### ISSUE TITLE
[Submission] La Piazza FFA (32)

### ISSUE THREAD

**Issue by technodono** [Warzone/PublicMaps#113]
### Map Name

La Piazza

### Map Description & Gamemode

This is a 32 player FFA map ported from the overcast community server to warzone.

I figured any maps that had not yet added to warzone I'd create issues for (except for a few maps)

### Map XML

https://gist.github.com/technodono/e1cf1edbfbe449ffc3bee196a21c4523

### Screenshot

![map](https://user-images.githubusercontent.com/22761234/210165777-8bd2397f-71ec-46de-b603-ed904b854a50.png)

### Map Download

[la_piazza.zip](https://github.com/Warzone/PublicMaps/files/10328536/la_piazza.zip)

### Checklist

- [X] Contains a map.xml file with valid syntax and formatting.
- [X] The map.xml uses proto 1.4.2 (older or legacy maps are exempt, so long as the XML works).
- [X] The map.xml explicitly sets the gamemode (for stat-tracking).
- [X] The map.xml has correctly credited the map authors and contributors.
- [X] The map contains a map.png file (290x246) without any resource pack or shaders applied.
- [X] The map was built for (or has been converted to) Minecraft 1.8.
- [X] Chunks have been pruned.
- [X] The map has been tested on a server running PGM.
- [X] I agree to submit this map under a commercial, CC BY-SA 4.0 license.

**Comment by BTKingly** [comment]
Thanks for the map submission!
