### ISSUE TITLE
[Submission] Kalahari Sanctuary FA (12v12) 

### ISSUE THREAD

**Issue by technodono** [Warzone/PublicMaps#114]
### Map Name

Kalahari Sanctuary

### Map Description & Gamemode

Gamemode: flag assault (formerly flag runners)

This is a new map that runs off the same premise as Royal rumble II & The Big Dig where you have to run the flags to the goals on the other end of the maps. Also an OCC port!

I've noticed you've categorised them as arcade for various reasons and I presume this will fall under that too!

(You may also need to update any other older flag runner maps with the new xml's from the OCC repo since the game name changed)

### Map XML

https://gist.github.com/technodono/8618bc47f5e2b392bb9bc169820c9305

### Screenshot

![map](https://user-images.githubusercontent.com/22761234/210165985-69427bf0-db78-443a-b98d-08643b7bf3cc.png)

### Map Download

[kalahari_sanctuary.zip](https://github.com/Warzone/PublicMaps/files/10328545/kalahari_sanctuary.zip)

### Checklist

- [X] Contains a map.xml file with valid syntax and formatting.
- [X] The map.xml uses proto 1.4.2 (older or legacy maps are exempt, so long as the XML works).
- [X] The map.xml explicitly sets the gamemode (for stat-tracking).
- [X] The map.xml has correctly credited the map authors and contributors.
- [X] The map contains a map.png file (290x246) without any resource pack or shaders applied.
- [X] The map was built for (or has been converted to) Minecraft 1.8.
- [X] Chunks have been pruned.
- [X] The map has been tested on a server running PGM.
- [X] I agree to submit this map under a commercial, CC BY-SA 4.0 license.

**Comment by BTKingly** [comment]
Thanks for the map submission!
