### ISSUE TITLE
[Submission] Zipline II: The next test KotF (24v24)

### ISSUE THREAD

**Issue by technodono** [Warzone/PublicMaps#115]
### Map Name

Zipline II: The next test

### Map Description & Gamemode

This is the sequel to zipline and is another port from the Overcast community server like Kalahari & La Piazza.

This map is a 24 v 24 King of the flag map that takes on a diagonal layout unlike the first zipline map and improves on the builds alot!

### Map XML

https://gist.github.com/technodono/17429e0ba9aba04fe5ef4d3070c47a8e

### Screenshot

![2022-08-19_16 24 39](https://user-images.githubusercontent.com/22761234/210166304-c3780221-e8d2-4995-855e-6dff1020862a.png)

### Map Download

[zipline_II_the_next_test.zip](https://github.com/Warzone/PublicMaps/files/10328558/zipline_II_the_next_test.zip)

### Checklist

- [X] Contains a map.xml file with valid syntax and formatting.
- [X] The map.xml uses proto 1.4.2 (older or legacy maps are exempt, so long as the XML works).
- [X] The map.xml explicitly sets the gamemode (for stat-tracking).
- [X] The map.xml has correctly credited the map authors and contributors.
- [X] The map contains a map.png file (290x246) without any resource pack or shaders applied.
- [X] The map was built for (or has been converted to) Minecraft 1.8.
- [X] Chunks have been pruned.
- [X] The map has been tested on a server running PGM.
- [X] I agree to submit this map under a commercial, CC BY-SA 4.0 license.

**Comment by BTKingly** [comment]
Thanks for the map submission!
