### ISSUE TITLE
[Submission] Frostbite RAGE

### ISSUE THREAD

**Issue by Tundrenn** [Warzone/PublicMaps#116]
### Map Name

Frostbite RAGE

### Map Description & Gamemode

snow themed rage ffa map 

### Map XML

https://gist.github.com/Tundrenn/14b9bb1c430f3ce0ba4ffb9d0c643b57

### Screenshot

![map](https://user-images.githubusercontent.com/94203319/210434631-15fff8c1-48c2-4405-92a3-0a9c743c6637.png)

### Map Download

[frostbite_rage.zip](https://github.com/Warzone/PublicMaps/files/10339564/frostbite_rage.zip)

### Checklist

- [X] Contains a map.xml file with valid syntax and formatting.
- [X] The map.xml uses proto 1.4.2 (older or legacy maps are exempt, so long as the XML works).
- [X] The map.xml explicitly sets the gamemode (for stat-tracking).
- [X] The map.xml has correctly credited the map authors and contributors.
- [X] The map contains a map.png file (290x246) without any resource pack or shaders applied.
- [X] The map was built for (or has been converted to) Minecraft 1.8.
- [X] Chunks have been pruned.
- [X] The map has been tested on a server running PGM.
- [X] I agree to submit this map under a commercial, CC BY-SA 4.0 license.

**Comment by TheRealPear** [comment]
Thanks for the map submission, I've went ahead and added it to the repo. In the meantime, I'll keep this open for any feedback that we might leave here
