### ISSUE TITLE
[Arcade] Foliage

### ISSUE THREAD

**Issue by Preinstalled** [Warzone/PublicMaps#119]
### Map Name

Foliage

### Map Description & Gamemode

Parkour FFA Map based around the theme of "Nature", first to reach the end wins. (12 Levels)

### Map XML

https://gist.github.com/Preinstalled/6da8baf2374dd2001825756ae303b303

### Screenshot

![2023-01-30_02 25 45](https://user-images.githubusercontent.com/75170440/215355481-97e1e4d3-b6f5-43e9-a09c-5bd92de4f7aa.png)
![2023-01-30_02 25 52](https://user-images.githubusercontent.com/75170440/215355484-d8c60cfa-5c7b-4bff-80c0-04a59eaaaf1a.png)
![2023-01-30_02 25 59](https://user-images.githubusercontent.com/75170440/215355485-1b25284c-cf25-493e-8b84-b9d133c34ba5.png)
![2023-01-30_02 26 09](https://user-images.githubusercontent.com/75170440/215355487-25e3fde5-690d-425c-ba76-e95eba3520dc.png)
![2023-01-30_02 26 13](https://user-images.githubusercontent.com/75170440/215355488-add9bed6-6de6-4f49-bec0-511d4ab550b9.png)

### Map Download

[Foliage.zip](https://github.com/Warzone/PublicMaps/files/10530857/Foliage.zip)

### Checklist

- [X] Contains a map.xml file with valid syntax and formatting.
- [X] The map.xml uses proto 1.4.2 (older or legacy maps are exempt, so long as the XML works).
- [X] The map.xml explicitly sets the gamemode (for stat-tracking).
- [X] The map.xml has correctly credited the map authors and contributors.
- [X] The map contains a map.png file (290x246) without any resource pack or shaders applied.
- [X] The map was built for (or has been converted to) Minecraft 1.8.
- [X] Chunks have been pruned.
- [X] The map has been tested on a server running PGM.
- [X] I agree to submit this map under a commercial, CC BY-SA 4.0 license.

**Comment by BTKingly** [comment]
Loaded, thanks for the submission
