### ISSUE TITLE
[KoTH] Crayons

### ISSUE THREAD

**Issue by Preinstalled** [Warzone/PublicMaps#120]
### Map Name

Crayons

### Map Description & Gamemode

KoTH Map with 3 Control Points. (3v3)

### Map XML

https://gist.github.com/Preinstalled/68098606c53342dffec0638119678038

### Screenshot

![map](https://user-images.githubusercontent.com/75170440/215355929-e265ca06-fc1b-4b9d-abda-4eabff1d30f7.png)
![2023-01-30_02 42 03](https://user-images.githubusercontent.com/75170440/215355946-ab5a5ae7-ae30-4f44-a548-20f24208c17c.png)
![2023-01-30_02 42 07](https://user-images.githubusercontent.com/75170440/215355947-3f370355-77f9-4d4f-be23-7ce6b4b800b5.png)
![2023-01-30_02 42 22](https://user-images.githubusercontent.com/75170440/215355948-dc2c9d49-e11a-46c9-a53b-59e05deee19f.png)

### Map Download

[Crayons.zip](https://github.com/Warzone/PublicMaps/files/10530887/Crayons.zip)

### Checklist

- [X] Contains a map.xml file with valid syntax and formatting.
- [X] The map.xml uses proto 1.4.2 (older or legacy maps are exempt, so long as the XML works).
- [X] The map.xml explicitly sets the gamemode (for stat-tracking).
- [X] The map.xml has correctly credited the map authors and contributors.
- [X] The map contains a map.png file (290x246) without any resource pack or shaders applied.
- [X] The map was built for (or has been converted to) Minecraft 1.8.
- [X] Chunks have been pruned.
- [X] The map has been tested on a server running PGM.
- [X] I agree to submit this map under a commercial, CC BY-SA 4.0 license.

**Comment by BTKingly** [comment]
Testing out the map here; it's quite difficult to use the launchpads successfully - more times than not I hit the roof, especially while sprinting. Is it possible that the opening could be enlarged?

**Comment by Preinstalled** [comment]
Here's the updated one with 3x3 openings instead of 1x1 so it's easier to use the jump pads:
[Crayons.zip](https://github.com/Warzone/PublicMaps/files/10549244/Crayons.zip)

**Comment by BTKingly** [comment]
Loaded, thanks for the submission [9d5bb6d](https://github.com/Warzone/PublicMaps/commit/9d5bb6d7581a80f80ad6c4517f7ba3144599d389)
