### ISSUE TITLE
[ARCADE] Sweetopia

### ISSUE THREAD

**Issue by Preinstalled** [Warzone/PublicMaps#121]
### Map Name

Sweetopia

### Map Description & Gamemode

Parkour FFA Map based around the theme of "Candy/Chocolate", first to reach the end wins. (18 Levels)

### Map XML

https://gist.github.com/Preinstalled/acecc019fc2f1b85fa21d3f06e20f765

### Screenshot

![2023-01-31_01 05 39](https://user-images.githubusercontent.com/75170440/215600514-e1b229e5-b465-429e-8981-77aff6b34472.png)
![2023-01-31_01 05 46](https://user-images.githubusercontent.com/75170440/215600553-a5c2241f-6e28-4468-867e-af1a38b85853.png)
![2023-01-31_01 05 51](https://user-images.githubusercontent.com/75170440/215600565-2b51c89b-eb75-48da-a23c-a06e1f692482.png)
![2023-01-31_01 06 03](https://user-images.githubusercontent.com/75170440/215600575-18b2bd94-f923-47e6-9e9a-5a6ccb33b841.png)
![2023-01-31_01 06 34](https://user-images.githubusercontent.com/75170440/215600588-c69b00b3-0f06-4a4a-9e4d-be30eb5f4a01.png)

### Map Download

[Sweetopia.zip](https://github.com/Warzone/PublicMaps/files/10540187/Sweetopia.zip)

### Checklist

- [X] Contains a map.xml file with valid syntax and formatting.
- [X] The map.xml uses proto 1.4.2 (older or legacy maps are exempt, so long as the XML works).
- [X] The map.xml explicitly sets the gamemode (for stat-tracking).
- [X] The map.xml has correctly credited the map authors and contributors.
- [X] The map contains a map.png file (290x246) without any resource pack or shaders applied.
- [X] The map was built for (or has been converted to) Minecraft 1.8.
- [X] Chunks have been pruned.
- [X] The map has been tested on a server running PGM.
- [X] I agree to submit this map under a commercial, CC BY-SA 4.0 license.

**Comment by BTKingly** [comment]
Loaded, thanks for the submission
