### ISSUE TITLE
[Arcade] Rush Hour

### ISSUE THREAD

**Issue by Preinstalled** [Warzone/PublicMaps#122]
### Map Name

Rush Hour

### Map Description & Gamemode

Parkour FFA Map based around the theme of "City", first to reach the end wins. (18 Levels)

### Map XML

https://gist.github.com/Preinstalled/21d097da714563a6b94177bfa276bbe1

### Screenshot

![2023-02-02_00 49 54](https://user-images.githubusercontent.com/75170440/216152690-78f1c450-9c7d-4a8e-84c5-ce07890db084.png)
![2023-02-02_00 49 59](https://user-images.githubusercontent.com/75170440/216152717-98d088de-ca95-4a35-8e64-8f2ec349cfd8.png)
![2023-02-02_00 49 39](https://user-images.githubusercontent.com/75170440/216152729-2e6efe1f-b2dc-4f9d-9e0c-c5d2533ea6d2.png)
![2023-02-02_00 50 27](https://user-images.githubusercontent.com/75170440/216152727-f22bbc41-e797-4836-b884-04a49eb71a79.png)

### Map Download

[Rush Hour.zip](https://github.com/Warzone/PublicMaps/files/10561273/Rush.Hour.zip)

### Checklist

- [X] Contains a map.xml file with valid syntax and formatting.
- [X] The map.xml uses proto 1.4.2 (older or legacy maps are exempt, so long as the XML works).
- [X] The map.xml explicitly sets the gamemode (for stat-tracking).
- [X] The map.xml has correctly credited the map authors and contributors.
- [X] The map contains a map.png file (290x246) without any resource pack or shaders applied.
- [X] The map was built for (or has been converted to) Minecraft 1.8.
- [X] Chunks have been pruned.
- [X] The map has been tested on a server running PGM.
- [X] I agree to submit this map under a commercial, CC BY-SA 4.0 license.

**Comment by BTKingly** [comment]
Loaded, thanks for the submission [9d5bb6d](https://github.com/Warzone/PublicMaps/commit/9d5bb6d7581a80f80ad6c4517f7ba3144599d389)
