### ISSUE TITLE
[Arcade] Snow Stadium

### ISSUE THREAD

**Issue by iMandoesnotknowhowtousethis** [Warzone/PublicMaps#123]
### Map Name

Snow Stadium

### Map Description & Gamemode

Spleef map
2v2 (can be more, when not played in tourney)
Spleef the opposing team off the map

### Map XML

https://gist.github.com/iMandoesnotknowhowtousethis/3325216e0d9c304242a8c8fd7859e5b3

### Screenshot

![map](https://user-images.githubusercontent.com/124184533/216154597-c9c01f4e-f5dd-48dc-b836-16a3a396e228.png)

### Map Download

https://cdn.discordapp.com/attachments/1067556951485075486/1069754050507182151/Snow_Stadium.zip

### Checklist

- [X] Contains a map.xml file with valid syntax and formatting.
- [X] The map.xml uses proto 1.4.2 (older or legacy maps are exempt, so long as the XML works).
- [X] The map.xml explicitly sets the gamemode (for stat-tracking).
- [X] The map.xml has correctly credited the map authors and contributors.
- [X] The map contains a map.png file (290x246) without any resource pack or shaders applied.
- [X] The map was built for (or has been converted to) Minecraft 1.8.
- [X] Chunks have been pruned.
- [X] The map has been tested on a server running PGM.
- [X] I agree to submit this map under a commercial, CC BY-SA 4.0 license.

**Comment by BTKingly** [comment]
Loaded, thanks for the submission [9d5bb6d](https://github.com/Warzone/PublicMaps/commit/9d5bb6d7581a80f80ad6c4517f7ba3144599d389)
