### ISSUE TITLE
[Arcade] Spleef Dojo

### ISSUE THREAD

**Issue by iMandoesnotknowhowtousethis** [Warzone/PublicMaps#124]
### Map Name

Spleef Dojo

### Map Description & Gamemode

Spleef map
2v2 (can be more, when not played in tourney)
Spleef the opposing team off the map

### Map XML

https://gist.github.com/iMandoesnotknowhowtousethis/8d7212bddd8d24c497dfda5019e949d8

### Screenshot

![map](https://user-images.githubusercontent.com/124184533/216164187-a3bc5609-4a5a-4d48-b1bc-ef3fbf91d342.png)

### Map Download

[Spleef_Dojo (1).zip](https://github.com/Warzone/PublicMaps/files/10561646/Spleef_Dojo.1.zip)

### Checklist

- [X] Contains a map.xml file with valid syntax and formatting.
- [X] The map.xml uses proto 1.4.2 (older or legacy maps are exempt, so long as the XML works).
- [X] The map.xml explicitly sets the gamemode (for stat-tracking).
- [X] The map.xml has correctly credited the map authors and contributors.
- [X] The map contains a map.png file (290x246) without any resource pack or shaders applied.
- [X] The map was built for (or has been converted to) Minecraft 1.8.
- [X] Chunks have been pruned.
- [X] The map has been tested on a server running PGM.
- [X] I agree to submit this map under a commercial, CC BY-SA 4.0 license.

**Comment by BTKingly** [comment]
Loaded, thanks for the submission [9d5bb6d](https://github.com/Warzone/PublicMaps/commit/9d5bb6d7581a80f80ad6c4517f7ba3144599d389)
