### ISSUE TITLE
Hobbit CTW upload

### ISSUE THREAD

**Issue by Guini2** [Warzone/PublicMaps#126]
### Map Name

Hobbit CTW

### Map Description & Gamemode

Fun Hobbit themed Capture the Wool map, with some middle islands and a chance to defend with good materials.

### Map XML

https://github.com/zzuf-fer/zzuf/blob/main/hobbit_ctw/map.xml

### Screenshot

https://imgur.com/a/0BPYyaE

### Map Download

[hobbit_ctw.zip](https://github.com/Warzone/PublicMaps/files/10832667/hobbit_ctw.zip)

### Checklist

- [X] Contains a map.xml file with valid syntax and formatting.
- [X] The map.xml uses proto 1.4.2 (older or legacy maps are exempt, so long as the XML works).
- [X] The map.xml explicitly sets the gamemode (for stat-tracking).
- [X] The map.xml has correctly credited the map authors and contributors.
- [X] The map contains a map.png file (290x246) without any resource pack or shaders applied.
- [X] The map was built for (or has been converted to) Minecraft 1.8.
- [X] Chunks have been pruned.
- [X] The map has been tested on a server running PGM.
- [X] I agree to submit this map under a commercial, CC BY-SA 4.0 license.

**Comment by TheRealPear** [comment]
Thanks for submitting! It has been loaded onto Warzone and will possibly be added into a pool in the future.
