### ISSUE TITLE
[Submission] Splegg

### ISSUE THREAD

**Issue by Fishywishi** [Warzone/PublicMaps#135]
### Map Name

Splegg

### Map Description & Gamemode

**Gamemode**: Arcade FFA Blitz
**Objective**: Map follows same premise as Spleef, breaking blocks under opponents to send them into the void, but differs in using an "Egg Shooter" that shoots eggs that break blocks. In addition, allows players to double jump every 10 seconds as a last lifeline or to go up layers after they've fallen. Recommended around 15 players in a match.

### Map XML

https://gist.github.com/Fishywishi/75786f573bd30965eba4bbf198ed4335

### Screenshot

![2024-03-23_21 31 05](https://github.com/Warzone/PublicMaps/assets/69370259/b273a595-e685-4d82-af0e-b43821ed4f23)
![2024-03-23_21 31 11](https://github.com/Warzone/PublicMaps/assets/69370259/3e43c886-bc74-46c6-9904-495856637824)
![2024-03-23_21 31 41](https://github.com/Warzone/PublicMaps/assets/69370259/2f864ee8-53d2-4cd7-acd5-4a1083478d47)

### Map Download

[Splegg Map Download](https://drive.google.com/file/d/1ZbWVhLgwIkdb3xqb1JB5wTW9WWIIc340/view?usp=sharing)

### Checklist

- [X] Contains a map.xml file with valid syntax and formatting.
- [X] The map.xml uses proto 1.4.2 (older or legacy maps are exempt, so long as the XML works).
- [X] The map.xml explicitly sets the gamemode (for stat-tracking).
- [X] The map.xml has correctly credited the map authors and contributors.
- [X] The map contains a map.png file (290x246) without any resource pack or shaders applied.
- [X] The map was built for (or has been converted to) Minecraft 1.8.
- [X] Chunks have been pruned.
- [X] The map has been tested on a server running PGM.
- [X] I agree to submit this map under a commercial, CC BY-SA 4.0 license.

**Comment by Wesdial** [comment]
Hey, thanks for sending in a submission, I've went ahead and added it to the repository and the Arcade rotation. Map looks good but just a heads up, your region file was not pruned correctly, no worries though, I've went ahead and pruned it for you, it went from 6.33MB to 96KB. Other than that, map looks great.
