### ISSUE TITLE
(Arcade/Any) Bookour

### ISSUE THREAD

**Issue by Fishywishi** [Warzone/PublicMaps#144]
### Map Name

Bookour

### Map Description & Gamemode

Bookour is a parkour race map where the objective is to reach the end first. The map is suitable for any player count.

### Map XML

https://gist.github.com/Fishywishi/bcbe104007e4181fcf414def1e9ff98e

### Screenshot

![2024-07-22_17 38 43](https://github.com/user-attachments/assets/adb116ae-0df3-4125-9df9-073bf1790efa)
![2024-07-22_17 38 46](https://github.com/user-attachments/assets/6195033b-8abc-491e-8582-cf75cffb3e2a)

### Map Download

[Drive Link](https://drive.google.com/file/d/19DPnKWjEWc9k0xu2tOkwxYtO8TytyHXb/view?usp=sharing)

### Checklist

- [X] Contains a map.xml file with valid syntax and formatting.
- [X] The map.xml uses proto `1.4.2` (older or legacy maps are exempt, so long as the XML works).
- [X] The map.xml explicitly sets the gamemode (for stat-tracking).
- [X] The map.xml has correctly credited the map authors and contributors.
- [X] The map contains a map.png file (`290x246`) without any resource pack or shaders applied.
- [X] The map was built for (or has been converted to) Minecraft 1.8.
- [X] The map has been [pruned](https://pgm.dev/docs/guides/preparing/pruning-chunks/).
- [X] The map has been tested on a server running PGM.
- [X] I agree to submit this map under CC BY-SA 4.0 license, as mentioned in the [README](https://github.com/Warzone/PublicMaps/blob/main/README.md#license).

**Comment by Wesdial** [comment]
This has been [loaded](https://github.com/Warzone/PublicMaps/commit/26d639e07908ec2ae9f077985d292d0aa0f00736) and added to the [Droplet](https://github.com/Warzone/PublicMaps/commit/2ac4efe11c3769093646e023eb995fb161723a5e) map pool. Thanks for sending in a submission!
