### ISSUE TITLE
[ARCADE/5v5] Thorn (Bow Spleef Map)

### ISSUE THREAD

**Issue by Preinstalled** [Warzone/PublicMaps#146]
### Map Name

Thorn

### Map Description & Gamemode

This is an arcade map submission for the map Thorn which is a bow spleef map best suited for 5v5 team scenario

### Map XML

https://gist.github.com/Preinstalled/685a5b6785b0ef48833136a6f2974e98

### Screenshot

![map](https://github.com/user-attachments/assets/37624f03-6da8-4d90-923f-67ec932ac909)

### Map Download

[Thorn.zip](https://github.com/user-attachments/files/16379460/Thorn.zip)

### Checklist

- [X] Contains a map.xml file with valid syntax and formatting.
- [X] The map.xml uses proto `1.4.2` (older or legacy maps are exempt, so long as the XML works).
- [X] The map.xml explicitly sets the gamemode (for stat-tracking).
- [X] The map.xml has correctly credited the map authors and contributors.
- [X] The map contains a map.png file (`290x246`) without any resource pack or shaders applied.
- [X] The map was built for (or has been converted to) Minecraft 1.8.
- [X] The map has been [pruned](https://pgm.dev/docs/guides/preparing/pruning-chunks/).
- [X] The map has been tested on a server running PGM.
- [X] I agree to submit this map under CC BY-SA 4.0 license, as mentioned in the [README](https://github.com/Warzone/PublicMaps/blob/main/README.md#license).

**Comment by Wesdial** [comment]
This has been [loaded](https://github.com/Warzone/PublicMaps/commit/4fe87058981ace8b1bd0bcf02cbae7a769de3bdf) and added to the [Arcade](https://github.com/Warzone/PublicMaps/commit/eafa54174d03ba26dddf93b90b1d53d79f7d1833) pool. Thanks for sending in a submission!
