### ISSUE TITLE
[DTW/5v5] Elysian Isles

### ISSUE THREAD

**Issue by Flamingfreak296** [Warzone/PublicMaps#148]
### Map Name

Elysian Isles

### Map Description & Gamemode

Elysian Isles is a DTW map with max expected player count to be 5v5

### Map XML

https://gist.github.com/Flamingfreak296/df88831020b6d26b4498171290e9de09

### Screenshot

![2024-08-10_15 05 08](https://github.com/user-attachments/assets/c34bed51-10ba-445a-8a85-8d2f9a6f346c)
![2024-08-10_08 33 48](https://github.com/user-attachments/assets/46490016-b6ea-42be-9fa7-83096bd8b681)
![2024-08-10_08 33 08](https://github.com/user-attachments/assets/f8f38b7e-6add-462e-b1ee-2520e24ee286)
![2024-08-10_08 29 39](https://github.com/user-attachments/assets/296bed30-4c92-4b14-89e4-bee08c56ebbf)
![2024-08-07_11 11 38](https://github.com/user-attachments/assets/759a92ef-b50b-4b07-bc8e-3e1aef53b7b0)

### Map Download

https://drive.google.com/file/d/1NVI5L9cuglqi6dXrLkdSQKtdBCLThIhh/view?usp=sharing

### Checklist

- [X] Contains a map.xml file with valid syntax and formatting.
- [X] The map.xml uses proto `1.4.2` (older or legacy maps are exempt, so long as the XML works).
- [X] The map.xml explicitly sets the gamemode (for stat-tracking).
- [X] The map.xml has correctly credited the map authors and contributors.
- [X] The map contains a map.png file (`290x246`) without any resource pack or shaders applied.
- [X] The map was built for (or has been converted to) Minecraft 1.8.
- [X] The map has been [pruned](https://pgm.dev/docs/guides/preparing/pruning-chunks/).
- [X] The map has been tested on a server running PGM.
- [X] I agree to submit this map under CC BY-SA 4.0 license, as mentioned in the [README](https://github.com/Warzone/PublicMaps/blob/main/README.md#license).

**Comment by Wesdial** [comment]
This map has been [loaded](https://github.com/Warzone/PublicMaps/commit/3bf20ba81d83da2107ef442d298c20796b30c5e4), thanks for sending in a submission! For the future, though, avoid using texture packs when taking screenshots for any map you submit or make a map.png for.
