### ISSUE TITLE
Teams are unable to place wools at spawn in Gyrus CTW

### ISSUE THREAD

**Issue by TheRealPear** [Warzone/PublicMaps#39]
### Map Name

Gyrus CTW

### Bug Type

XML

### Description

While playing this map earlier today on Warzone, we ran into an issue where two teams (blue and green) couldn't place one or any of the wools they've captured at their spawn. My team and an another (red and yellow) could place wools. I am assuming this has something to do with the filters in the map.xml file. I've also looked through the xml, but I couldn't tell where exactly was causing this issue.

### Screenshots or Videos (if applicable)

(Special thanks to Eraaaks and SnowyXD_ for sharing their screenshots)

![image](https://user-images.githubusercontent.com/20259871/155897222-c009a7b9-c630-47f3-a7b8-0096ca433dd4.png)
![image](https://user-images.githubusercontent.com/20259871/155897224-c3852661-76e0-48a0-a805-748455883515.png)

**Comment by CrazyisCreeps** [comment]
It was a little confusing, but I think whoever made the xml messed up the monument locations for green and blue team. Thanks for making an issue!
