### ISSUE TITLE
Dracula - Improve spawns

### ISSUE THREAD

**Issue by CrazyisCreeps** [Warzone/PublicMaps#77]
### Map Name

Dracula

### Suggestion

Cobwebs at spawn at bypass-able, maybe implement respawn timer and scrap webs?

Would also be nice to see crafting tables in spawns, as it's quite hard to craft armour from the gold nuggets in a timely fashion. There are already deny entry filters on the spawns

**Comment by CrazyisCreeps** [comment]
Updating this, I actually feel like the crafting tables are at an okay place, but yea the spawns need fixing

**Comment by TheRealPear** [comment]
What would you change the respawn delay to account for the cobwebs being removed?

**Comment by TBG1000** [comment]
I figure after playing this just now, increasing it by 2.5 seconds should be good. 

I calculated that going through a single web block while sprinting takes about 4 seconds, while going through the corner of two webs (as indicated below) takes about 3.

![image](https://user-images.githubusercontent.com/46306028/183228763-b038bdff-d5e6-4e5c-91d8-4cc7514a436f.png)

**Comment by bearyr** [comment]
That sounds like a good change - I'll also toss up adding appropriate barriers to prevent players from bypassing the cobwebs from the sides by the exterior parts of spawn as well.

![image](https://user-images.githubusercontent.com/80069984/183229000-3c08e903-d0c0-46a5-929f-16d5dff51c4b.png)

**Comment by bearyr** [comment]
World region updated to remove cobwebs, implement communal chests at spawn. 
Respawn delay was increased to 4.5 seconds - will leave the issue open to see how the changes are received.

**Comment by TheRealPear** [comment]
Going to close this for inactivity now. This map has been played over a period of several months with no complaint, so I think it's safe to say this changes are well received.
