### ISSUE TITLE
[Contest Submission] [CTF/8v8] Pipes and Punters

### ISSUE THREAD

**Issue by Cazadorian** [Warzone/PublicMaps#79]
### Map Name

Pipes and Punters

### Map Description & Gamemode

This map is an 8v8 Flag Football style CTF in which a singular flag spawns in the centre of the map which both teams have to fight over. To score the flag must be carried to the net at the back of either team's side(which is denoted by a Warp Pipe on this specific map). Unlike most flag football maps this map does not make use of the "Rafter" mechanics and instead has specific dedicated spawns onto the playable area. 

### Map XML

https://gist.github.com/Cazadorian/f39f21b9b11fa11212cca5b2f015f4f3

### Screenshot

[Screenshots](https://imgur.com/a/ibpUJOS)

![map.png](https://user-images.githubusercontent.com/73002842/173429943-4cc9befe-5bb8-4a55-aa53-5b27dc45d4a5.png)

### Map Download

[Pipes and Punters.zip](https://github.com/Warzone/PublicMaps/files/8893586/Pipes.and.Punters.zip)

### Checklist

- [X] Contains a map.xml file with valid syntax and formatting.
- [X] The map.xml uses proto 1.4.0 or above (older or legacy maps are exempt, so long as the XML works).
- [X] The map.xml explicitly sets the gamemode (for stat-tracking).
- [X] The map.xml has correctly credited the map authors and contributors.
- [X] Contains map.png file (290x246).
- [X] The map was built for (or has been converted to) Minecraft 1.8.
- [X] Chunks have been pruned.
- [X] The map has been tested on a server running PGM.
- [X] I agree to submit this map under a commercial, CC BY-SA 4.0 license.

**Comment by TheRealPear** [comment]
[Added to PublicMaps](https://github.com/Warzone/PublicMaps/commit/9cae812021071c0de9b35803019568cc0bf7bd34)
