### ISSUE TITLE
[Contest Submission] [CTW/8v8] Deciduous Nights

### ISSUE THREAD

**Issue by Cazadorian** [Warzone/PublicMaps#80]
### Map Name

Deciduous Nights

### Map Description & Gamemode

This map is a simple 1 wool per team CTW intended for smaller player counts such as 8v8. The key unique thing about this map is that every single full block within the playable area is a type of clay. The map should hopefully play like a standard CTW.

### Map XML

https://gist.github.com/Cazadorian/97c94b8a62f83d3e1a3e76133225e3be

### Screenshot

[Screenshots](https://imgur.com/a/ILed12W)

![map.png](https://user-images.githubusercontent.com/73002842/173430064-a15343cd-addd-484c-8072-0dac45299685.png)

### Map Download

[Deciduous Nights.zip](https://github.com/Warzone/PublicMaps/files/8893638/Deciduous.Nights.zip)

### Checklist

- [X] Contains a map.xml file with valid syntax and formatting.
- [X] The map.xml uses proto 1.4.0 or above (older or legacy maps are exempt, so long as the XML works).
- [X] The map.xml explicitly sets the gamemode (for stat-tracking).
- [X] The map.xml has correctly credited the map authors and contributors.
- [X] Contains map.png file (290x246).
- [X] The map was built for (or has been converted to) Minecraft 1.8.
- [X] Chunks have been pruned.
- [X] The map has been tested on a server running PGM.
- [X] I agree to submit this map under a commercial, CC BY-SA 4.0 license.

**Comment by TheRealPear** [comment]
[Added to PublicMaps](https://github.com/Warzone/PublicMaps/commit/9cae812021071c0de9b35803019568cc0bf7bd34)
