### ISSUE TITLE
[Contest Submission] [DTC/8v8] Hearts of Atlantis

### ISSUE THREAD

**Issue by Cazadorian** [Warzone/PublicMaps#81]
### Map Name

Hearts of Atlantis

### Map Description & Gamemode

This map is an 8v8 DTC designed with a unique layout and shape to make it play better at lower player counts than are standard for DTC maps. The map otherwise is a rather standard TNTless DTC map.

### Map XML

https://gist.github.com/Cazadorian/8bd6bf8abe671b9307c09718fd13ca41

### Screenshot

[Screenshots](https://imgur.com/a/Kj2Wqua)

![map.png](https://user-images.githubusercontent.com/73002842/173430141-032e3a24-ea37-40ec-82ce-11e043b77e72.png)

### Map Download

[Hearts of Atlantis.zip](https://github.com/Warzone/PublicMaps/files/8893646/Hearts.of.Atlantis.zip)

### Checklist

- [X] Contains a map.xml file with valid syntax and formatting.
- [X] The map.xml uses proto 1.4.0 or above (older or legacy maps are exempt, so long as the XML works).
- [X] The map.xml explicitly sets the gamemode (for stat-tracking).
- [X] The map.xml has correctly credited the map authors and contributors.
- [X] Contains map.png file (290x246).
- [X] The map was built for (or has been converted to) Minecraft 1.8.
- [X] Chunks have been pruned.
- [X] The map has been tested on a server running PGM.
- [X] I agree to submit this map under a commercial, CC BY-SA 4.0 license.

**Comment by TheRealPear** [comment]
[Added to PublicMaps](https://github.com/Warzone/PublicMaps/commit/9cae812021071c0de9b35803019568cc0bf7bd34)
