### ISSUE TITLE
[Contest Map Submission] [KoTF/12v12] Flaterns

### ISSUE THREAD

**Issue by Flamingfreak296** [Warzone/PublicMaps#86]
### Map Name

Flaterns

### Map Description & Gamemode

This map is a 12v12 KoTF map, made with a jungle overground theme.
Its made of unique shaped platforms, consists of 3 floors and has jump pads around the map.
players are given speed-1 effect to move fast while "Flag holders" get speed removed from them (this is done to be able to make jumps across platforms). 
Its a rather lovely looking map.

### Map XML

https://gist.github.com/Flamingfreak296/ce392ac57581b46e6988aadc35795456

### Screenshot

**SCREENSHOTS**
https://imgur.com/a/EcC3AsI

**MAP.PNG**

![map](https://user-images.githubusercontent.com/86233264/174634454-7d709000-112c-4a2f-87eb-1c9726fed328.png)

### Map Download

[Flaterns.zip](https://github.com/Warzone/PublicMaps/files/9033125/Flaterns.zip)

### Checklist

- [X] Contains a map.xml file with valid syntax and formatting.
- [X] The map.xml uses proto 1.4.0 or above (older or legacy maps are exempt, so long as the XML works).
- [X] The map.xml explicitly sets the gamemode (for stat-tracking).
- [X] The map.xml has correctly credited the map authors and contributors.
- [X] Contains map.png file (290x246).
- [X] The map was built for (or has been converted to) Minecraft 1.8.
- [X] Chunks have been pruned.
- [X] The map has been tested on a server running PGM.
- [X] I agree to submit this map under a commercial, CC BY-SA 4.0 license.

**Comment by Flamingfreak296** [comment]
I added flag platform regions to prevent block placing in them in the XML. check to gist link in **Map XML**

**Comment by TheRealPear** [comment]
[Added to PublicMaps](https://github.com/Warzone/PublicMaps/commit/c62af94ea39b48109f53eefdb8bfa3a767a3b655)
