### ISSUE TITLE
[Gameplay] Limbo II - Spawn Regions

### ISSUE THREAD

**Issue by residal** [Warzone/PublicMaps#88]
### Map Name

Limbo II

### Suggestion

Prevent the opposition from entering the other teams spawn. Players can currently sit behind the enemy teams spawnpoint and hit them as soon as they respawn, which negatively affects gameplay.

**Comment by Wesdial** [comment]
Fixed, refer to [(this)](https://github.com/Warzone/PublicMaps/commit/4b783af161861dd53925d59af5a06ae2542ee7d2). Thanks for making an issue.
