### ISSUE TITLE
[Gameplay] Swamp Land | Border Regions & Item Drops

### ISSUE THREAD

**Issue by residal** [Warzone/PublicMaps#94]
### Map Name

Swamp Land

### Suggestion

Border regions should be implemented to discourage the players in the game from hiding to avoid conflict. These regions should commence a few minutes after the walls are down, and slowly close in on the middle of the map over time. 

Item drops should also be enabled, because it would be beneficial for someone who beats an enemy to receive their items upon death.

**Comment by Wesdial** [comment]
- Added a world border, will shrink after 7 minutes into the match (after the walls drop.) Will take another 7 minutes to fully close in on the center.
- Reduced the time limit from 20 minutes to 16 minutes.
- Reduced the build height to prevent players from sky camping.
- Fixed an issue where certain teams could build at the map's borders, and exit it.

> Item drops should also be enabled, because it would be beneficial for someone who beats an enemy to receive their items upon death.

Item drops should already be enabled, but PGM already prevents Classes / Kits from dropping on death. I have zero control over that. (I think) Even if I did have control, you would have to consider players taking that to their advantage and abusing it, they could do that by killing themselves and respawn over and over again to duplicate their items.
