### ISSUE TITLE
[Gameplay] Golden Drought III - Prevent team griefing at spawn

### ISSUE THREAD

**Issue by residal** [Warzone/PublicMaps#95]
### Map Name

Golden Drought III

### Suggestion

Marked in bedrock and originally sandstone, teammates are able to mine or place blocks and ultimately create a trap that kills their own teammates. 

Spawn regions should be upgraded to prevent any player from breaking or placing blocks in the few blocks in front of spawn. 

_I placed bedrock in this match following a player who attempted to construct a hole that would kill off their team._

### Screenshots or Videos (if applicable)

![2022-07-17_09 06 12](https://user-images.githubusercontent.com/55336990/179374643-adc97683-ee97-4ff4-ae82-6b473ae58323.png)

**Comment by BTKingly** [comment]
Sorry, I might not be understanding the issue entirely. Players cannot mine the bridge over the void, the area which you have indicated is the start of the map - not over the void.

**Comment by residal** [comment]
> Sorry, I might not be understanding the issue entirely. Players cannot mine the bridge over the void, the area which you have indicated is the start of the map - not over the void.

They are able to mine the area marked in bedrock, which was originally sandstone on the match that this screenshot was taken on. After noticing a teammate begin to mine out that area and make a death trap for their teammates, I covered it up with bedrock to prevent the same behavior.

That is the area I'm talking about, apologies if I was confusing.

**Comment by BTKingly** [comment]
Oops, sorry for the late response. The area indicated isn't over the void; less of a worry, and won't kill a player to fall into a couple of mined blocks. In my opinion, this could happen anywhere on the map (players digging it out).

It's intended for players to mine out the map - closing this. (that being said, if mining any part of the map is done with malicious intent, that would fall under moderation)
